### ISSUE TITLE
Freeze on latest CIA version release

### ISSUE THREAD

**Issue by Joelgp83** [nop90/Opentyrian-3ds#1]
Hey there, ran into a freezing issue on the latest verison.  System is an O3ds, AL9h + Luma, 11.3 sysnand.  Booted game, started a 1player Arcade mode, then had to pause game and set it aside (left system open, sleep mode was not used).  

10 minutes later, came back to a locked up system.  Non-responsive, had to hard reboot.

**Comment by nop90** [comment]
Freeze happens for problems with the GPU.

I changed the SDL_Video code to be more stable. I'm testing it and I'll probably release an update of the game in the next days.

But a little chance of freeze remains. I'm closing this, but i'll continue to improve the code if I can.
